export const FETCH_SUGGESTIONS_PENDING = 'FETCH_SUGGESTIONS_PENDING';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS';
export const FETCH_SUGGESTIONS_ERROR = 'FETCH_SUGGESTIONS_ERROR';
